config/routes.rb
Rails.application.routes.draw do
  resources :vocabularies do
    collection do
      get 'search'
    end
  end
  resources :vocabularies, only: [:index, :create, :destroy, :edit, :update, :show]
  root to: "vocabularies#index"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  validates :word, presence: true
  validates :meaning, presence: true
  validates :level, presence: true

  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  def index
    @vocabulary = Vocabulary.new
    @vocabularies = Vocabulary.all.order("created_at DESC")
    @paginatable_array = Kaminari.paginate_array(@vocabularies).page(params[:page]).per(15)
    @q = Vocabulary.ransack(params[:q])
  end

  def create
    if user_signed_in?
      @vocabulary = Vocabulary.new(vocabulary_params)
      if @vocabulary.save
        redirect_to root_path
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @vocabulary = Vocabulary.find(params[:id])
    if @vocabulary.destroy
      redirect_to root_path
    end
  end

  def edit
    @vocabulary = Vocabulary.find(params[:id])
  end

  def update
    vocabulary = Vocabulary.find(params[:id])
    if vocabulary.update(vocabulary_params)
      redirect_to root_path
    else
      render edit
    end
  end

  def search
    @q = Vocabulary.ransack(params[:q])
    @vocabularies = @q.result
  end

  def show
    @vocabularies = Vocabulary.where(params[:id])
  end

  private
  def vocabulary_params
    params.require(:vocabulary).permit(:word, :meaning, :level).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWordBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- リセットCSS -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="header">
    <div class="header-left">
      <a href="http://localhost:3000/">Memory Bread</a>
    </div>
    <div class="header-middle">
      <a href="#" id="choose">言語選択</a>
    </div>
    <div class="header-right">
      <% if user_signed_in? %>
          <%= "#{current_user.nickname}さんは、ログインしています" %>
          <%= link_to "ログアウト" , destroy_user_session_path, method: :delete %><br>
      <% else %>
          <%= link_to "新規登録" , new_user_registration_path %>
          <%= link_to "ログイン" , new_user_session_path %><br>
      <% end %>
    </div>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vocabularies/_model.html.erb
<tr>
  <td>apple</td>
  <td>りんご</td>
  <td>1</td>
  <td><%= link_to "編集", '#' %></td>
  <td><%= link_to "削除", '#' %></td>
</tr>
<tr>
  <td>absentminded</td>
  <td>上の空の、ぼんやりしている</td>
  <td>3</td>
  <td><%= link_to "編集", '#' %></td>
  <td><%= link_to "削除", '#' %></td>
</tr>

app/views/vocabularies/edit.html.erb
<div class="edit-all">
  <h3>編集する</h3>
  <%= form_with(model: @vocabulary, local: true) do |form| %>
    <div class="edit-form">
      <div>
        <%= form.text_field :word %>
      </div>
      <div>
        <%= form.text_area :meaning %>
      </div>
      <div>
        <%= form.text_field :level %>
      </div>
      <div>
        <%= form.submit "編集" %>
      </div>
    </div>
    <% end %>
</div>

app/views/vocabularies/index.html.erb
<div class="all">
  <div class="main">
    <!-- 単語登録 -->
      <div class="new-word">
        <%= form_with(model: @vocabulary, local: true ) do |f| %>
          <%= f.text_field :word, placeholder: "単語を入力" %>
          <%= f.text_field :meaning, placeholder: "意味を入力" %>
          <%= f.text_field :level, placeholder: "難易度(1~5)入力" %>
          <%= f.submit "POST" , value: "登録" %>
        <% end %>
      </div>

    <!-- 単語検索 -->
    <div class="search-word">
      <% if user_signed_in? %>
        <%= search_form_for(@q, url: search_vocabularies_path) do |f| %>
          <%= f.search_field :word_cont, placeholder: '単語名' %><br>
          <%= f.search_field :meaning_cont, placeholder: '単語の意味' %><br>
          <%= f.search_field :level_eq, placeholder: '難易度' %><br>
          <%= f.submit '検索'%><br>
          <div class="memory">
            <%= link_to "記憶学習をする！！" , vocabulary_path(current_user.id) %>
          </div>
        <% end %>
      <% else %>
        <%= search_form_for(@q, url: '#') do |f| %>
          <%= f.search_field :word_cont, placeholder: '単語名' %><br>
          <%= f.search_field :meaning_cont, placeholder: '単語の意味' %><br>
          <%= f.search_field :level_eq, placeholder: '難易度' %><br>
          <%= f.submit '検索' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <table border="1" style="border-collapse: collapse" , class="show-words">
    <tr>
      <th class="word-label">単語</th>
      <th class="meaning-label">意味</th>
      <th class="level-label">難易度</th>
    </tr>

    <% if user_signed_in? %>
      <% @paginatable_array.each do |vocabulary| %>
        <% if current_user.id == vocabulary.user_id %>
          <tr>
            <td><%= vocabulary.word %></td>
            <td><%= vocabulary.meaning %></td>
            <td><%= vocabulary.level %></td>
            <td class="edit"><%= link_to "編集", edit_vocabulary_path(vocabulary.id) %></td>
            <td class="delete"><%= link_to "削除" , vocabulary_path(vocabulary.id), method: :delete %></td>
          </tr>
        <% end %>
      <% end %>
    <% else %>
      <%= render partial: 'model' %>
    <% end %>
  </table>



  <div class="page-nations">
    <%= page_entries_info @paginatable_array %>
    <%= paginate @paginatable_array %>
  </div>
</div>

app/views/vocabularies/search.html.erb
<table border="1" style="border-collapse: collapse" , class="show-words">
  <tr>
    <th class="word-label">単語</th>
    <th class="meaning-label">意味</th>
    <th class="level-label">難易度</th>
  </tr>
  <% @vocabularies.each do |vocabulary| %>
    <tr>
      <td><%= vocabulary.word %></td>
      <td><%= vocabulary.meaning %></td>
      <td><%= vocabulary.level %></td>
    </tr>
  <% end %>
</table>


  <%= link_to "トップに戻る" , root_path %>

app/views/vocabularies/show.html.erb
 <!-- require “date” -->

  <table border="1" style="border-collapse: collapse" , class="show-words">
    <tr>
      <th class="word-label">単語</th>
      <th class="meaning-label">意味</th>
      <th class="level-label">難易度</th>
    </tr>
    <% @vocabularies.each do |vocabulary| %>
      <% if vocabulary.created_at.strftime('%Y/%m/%d') == Date.today.yesterday.strftime('%Y/%m/%d') %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.meaning %></td>
          <td><%= vocabulary.level %></td>
        </tr>
      <% end %>

      <% if vocabulary.created_at.strftime('%Y/%m/%d')==Date.today.ago(4.days).strftime('%Y/%m/%d') %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.meaning %></td>
          <td><%= vocabulary.level %></td>
        </tr>
      <% end %>

      <% if vocabulary.created_at.strftime('%Y/%m/%d')==Date.today.ago(7.days).strftime('%Y/%m/%d') %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.meaning %></td>
          <td><%= vocabulary.level %></td>
        </tr>
      <% end %>

      <% if vocabulary.created_at.strftime('%Y/%m/%d')==Date.today.ago(11.days).strftime('%Y/%m/%d') %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.meaning %></td>
          <td><%= vocabulary.level %></td>
        </tr>
      <% end %>

      <% if vocabulary.created_at.strftime('%Y/%m/%d')==Date.today.ago(15.days).strftime('%Y/%m/%d') %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.meaning %></td>
          <td><%= vocabulary.level %></td>
        </tr>
      <% end %>

      <% if vocabulary.created_at.strftime('%Y/%m/%d')==Date.today.ago(20.days).strftime('%Y/%m/%d') %>
        <tr>
          <td><%= vocabulary.word %></td>
          <td><%= vocabulary.meaning %></td>
          <td><%= vocabulary.level %></td>
        </tr>
      <% end %>
    <% end %>
  </table>


  <%= link_to "トップに戻る" , root_path %>